### ISSUE TITLE
Wrong header in the bibliography

### ISSUE THREAD

**Issue by ifarup** [COPCSE-NTNU/thesis-NTNU#21]
The bibliography gets the header of the last chapter instead of saying 'Bibliography' as it should.

**Comment by ifarup** [comment]
Very strange. Seems to appear only on last page of bibliography if that page has the layout of an odd numbered page.

**Comment by ifarup** [comment]
Any ideas? @Hexoplon @barskern @marni

**Comment by barskern** [comment]
Do you have a document where the mentioned error occurs? @ifarup

**Comment by R0flcopt3r** [comment]
Testing this on my machine with fedora and everything seems fine.

I compiled the standard document from the repository with no modifications, the bibligraphy ended up relative page 21 and absolute page 39, and the heading is correct.

See attached file:
![dmc03qnf](https://user-images.githubusercontent.com/12752060/79856684-f0847100-83cc-11ea-8e77-a26415e951ab.png)

**Comment by ifarup** [comment]
Created a new branch 'issue-21' that demonstrates the problem. Play with (un)commenting some of the \nocites{} in thesis.tex in order to get the bibliography span different number of pages and observe the headers (not headings!)

**Comment by Hexoplon** [comment]
The same issues seems to be occuring with the code listings if it extends over three pages. It then has _`Tables`_ as its header.

**Comment by Hexoplon** [comment]
Fixed issue in #22 

The \printbibliography command seems to create its own "environment" when printing that ends as soon as the contents are printed. After this, the preceeding chapter will "take over". This creates issues with headers if the bibliography ends on an odd numbered page, other than the first page of the bibliography. This issue is avoided by printing the bibliography without a heading, and creating a chapter instead.

The issue with the code listings was addressed by changing the behaviour of the \lstlistoflistings command to create an unnumbered chapter, instead of a float like the original source code in the package does.

**Comment by ifarup** [comment]
Thanks, @Hexoplon !

**Comment by sanderob** [comment]
A similar problem appears if the list of acronyms reaches a length of 3 pages: the header on the third page of the list of acronyms (and any odd page after this?) shows "Tables" instead of "Acronyms". Do you believe this issue has a solution similar to the solution regarding the code listings, @Hexoplon?

EDIT: This is now moved to issue #44 with a corresponding PR.
